<Project Sdk="Microsoft.NET.Sdk">
  
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <OutputType>Library</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <NoStdLib>false</NoStdLib>
    <LangVersion>latest</LangVersion>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Lib.Harmony" Version="2.3.6" ExcludeAssets="runtime" />
    <PackageReference Include="Lib.InGameWiki" Version="16.0.1" />
    <PackageReference Include="Krafs.Rimworld.Ref" Version="1.6.4528" />
    
    <!-- Ungodly hack to access rimworld private properties & methods -->
    <PackageReference Include="Krafs.Publicizer" Version="2.3.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <Publicize Include="Assembly-CSharp" />
  </ItemGroup>

  <!-- You must build Power Poles assembly first! -->
  <ItemGroup>
    <Reference Include="Power Poles">
      <HintPath>..\..\..\Power-Poles\$(RimworldVersion)\Assemblies\Power Poles.dll</HintPath>
    </Reference>
  </ItemGroup>

  <!-- Output -->
  <PropertyGroup>
    <DebugType>none</DebugType>
    <OutputPath>..\..\$(RimworldVersion)\Assemblies\</OutputPath>
    <Optimize>true</Optimize>
    <DefineConstants>TRACE</DefineConstants>
  </PropertyGroup>

</Project>